---
title: "p8105_hw5_coo2124"
author: "Christiana Odewumi"
output: github_document
---

# Load necessary libraries 
```{r}
library(tidyverse)    
library(broom)        
library(purrr)
library(rvest)

set.seed(1)

knitr::opts_chunk$set(
        echo = TRUE,
        warning = FALSE,
        fig.width = 6,
        fig.asp = .6,
        out.width = "90%"
)

theme_set (theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## problem 1

Function to simulate birthdays and checks whether there are duplicate birthdays in the group
```{r}
simulate_shared_birthday = function(n) {
  birthdays = sample(1:365, n, replace = TRUE)
  has_duplicate = any(duplicated(birthdays))
}
```


Run this function 10,000 times for each group size between 2 and 50.
```{r}
compute_duplicate_probability <- function(n) {
  simulations <- map_lgl(1:10000, ~simulate_shared_birthday(n))
  prob <- mean(simulations)
  
  tibble(
    group_size = n,
    prob_duplicate = prob
  )
}

result_final <- map_dfr(2:50, compute_duplicate_probability)
result_final
```


Make a plot showing the probability as a function of group size, and comment on your results.
```{r}
ggplot(result_final, aes(x = group_size, y = prob_duplicate)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Probability of People Sharing a Birthday",
    x = "Group Size",
    y = "Probability"
  ) +
  theme_minimal()
```

## problem 2
